#!/bin/sh
### BEGIN INIT INFO
# Provides:          pidentd-run-dir
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     S
# Default-Stop:      
# Short-Description: setup for pidentd
# Description:       create /var/run/identd for pidentd
### END INIT INFO

[ -x /usr/sbin/identd ] || exit 0

case "$1" in
	start|restart|reload|force-reload)
		mkdir -p /var/run/identd
		chown identd:nogroup /var/run/identd
		chmod 755 /var/run/identd
	;;
	stop)
	;;
	status)
		test -d /var/run/identd || exit 4
		exit 0
	;;
esac
